# -*- coding: utf-8 -*-
"""project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ryhHXoMr4qckDqvzdrXUfuWJV1Kvyb_X
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv('/content/NFLX[1].csv')
df.head(2)

df.shape

df.size

df.info()

df.describe()

df.isnull().sum()

# Creation of target column
#1 = Next day price UP
#0 = Next day price DOWN
df['Target'] = np.where(df['Close'].shift(-1) > df['Close'], 1, 0)
df.dropna(inplace=True)

df.describe()

#Removaing Unnecessary Columns
df.drop(['Date', 'Adj Close'], axis=1, inplace=True)

# Separate Features & Target
x = df.drop('Target', axis=1)
y = df['Target']

x

print(x)

y

print(x)

# Feature scalling
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd # Ensure pandas is imported for DataFrame operations

scaler = StandardScaler()

# Create a definitive copy of the dataframe to ensure consistent processing for x and y
processed_df = df.copy()

# Ensure 'Target' column is explicitly created and then NaNs are handled to align x and y
# This step accounts for cases where df state might be inconsistent from previous cell executions
if 'Target' not in processed_df.columns:
    processed_df['Target'] = np.where(processed_df['Close'].shift(-1) > processed_df['Close'], 1, 0)

# Drop any rows with NaN values across all relevant columns to ensure x and y have the same length
# This handles potential NaNs introduced by shift or existing in other columns.
processed_df.dropna(inplace=True)

# Define y (target) from the cleaned and aligned dataframe
y = processed_df['Target'].values

# Define x (features) - explicitly select feature columns and ensure 'Target' is not included
# Assuming features are 'Open', 'High', 'Low', 'Close', 'Volume'
feature_columns = ['Open', 'High', 'Low', 'Close', 'Volume']
x_df = processed_df[feature_columns]

# Convert the feature DataFrame to a NumPy array for scaling
x = x_df.values

# Scale the features
x = scaler.fit_transform(x)

# The 'x' and 'y' variables have already been correctly prepared and scaled in the previous cell (UFqkHmUZ76Cr).
# Re-assigning them here caused an inconsistency in their number of samples, and is redundant.
# This cell is no longer needed to re-define x and y. Its content has been commented out to prevent issues.

print("Shape of x:",x.shape)
print("Shape of y:",y.shape)

print("Shape of x:",x.shape)
print("Shape of y:",y.shape)

# training and testing
from sklearn.model_selection import train_test_split
import numpy as np

# x and y are already prepared and scaled from the previous cell (UFqkHmUZ76Cr)
# So, we can directly use them for train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y,test_size=0.20,random_state=200)

print("Shape of X_Train:" ,x_train.shape )
print("Shape of X_Test:" , x_test.shape)
print("Shape of Y_Train:" , y_train.shape)
print("Shape of Y_Test:" , y_test.shape)

"""# Implementing ML model"""

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(x_train)
x_train=sc.transform(x_train)
x_test=sc.transform(x_test)

"""# LogisticRegression"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Scaling (Important)
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

# Model
lr = LogisticRegression(max_iter=500)
lr.fit(x_train, y_train)

# Prediction
y_pred_lr = lr.predict(x_test)

# Metrics
acc = accuracy_score(y_test, y_pred_lr)
print("Accuracy:", acc)

prec = precision_score(y_test, y_pred_lr)
print("Precision:", prec)

rec = recall_score(y_test, y_pred_lr)
print("Recall:", rec)

f1 = f1_score(y_test, y_pred_lr)
print("F1 Score:", f1)

from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
x_pred = lr.predict(x_test)
print("MSE VALUE:", mean_squared_error(y_test, x_pred))
print("MAE:",mean_absolute_error(y_test,x_pred))
print("RMSE:",np.sqrt(mean_squared_error(y_test,x_pred)))
print("R2 SCORE:",r2_score(y_test,x_pred))

# creation of confussion matrix
from sklearn.metrics import confusion_matrix
# Use y_pred_lr, which contains the predictions from the Logistic Regression model.
cm=confusion_matrix(y_test,y_pred_lr)
cm

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred_lr) # Calculate confusion matrix for Logistic Regression

plt.figure(figsize=(5,4))
sns.heatmap(cm,
            annot=True,
            fmt='d',
            cmap='Purples',
            xticklabels=["Down (0)", "Up (1)"],
            yticklabels=["Down (0)", "Up (1)"])

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix - Logistic Regression")
plt.show()

"""# DecisionTreeClassifier"""

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=51)
dt.fit(x_train, y_train)

y_pred_dt = dt.predict(x_test)

from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
acc=accuracy_score(y_test,y_pred_dt)
print("Accuracy:",acc)
prec=precision_score(y_test,y_pred_dt)
print("Precision:",prec)
rec=recall_score(y_test,y_pred_dt)
print("Recall:",rec)
f1=f1_score(y_test,y_pred_dt)
print("f1 score:",f1)

cm = confusion_matrix(y_test, y_pred_dt)
print("Confusion Matrix:\n", cm)

plt.figure(figsize=(5,4))
sns.heatmap(cm,
            annot=True,
            fmt='d',
            cmap='Blues',
            xticklabels=["Down (0)", "Up (1)"],
            yticklabels=["Down (0)", "Up (1)"])

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix - Decision Tree")
plt.show()

"""# RandomForestClassifier"""

# Implementing ml model
# Train RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier

rm_g= RandomForestClassifier(n_estimators=100,criterion='entropy')
rm_g.fit(x_train,y_train)
rm_g.score(x_test,y_test)

from sklearn.metrics import confusion_matrix,classification_report
rm_g.fit(x_train,y_train)
rm_g.score(x_test,y_test)

# evalution matics
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score
rm_g.fit(x_train,y_train)
y_pred = rm_g.predict(x_test)

param_grid = {
    'n_estimators': [100, 200, 300,500],
    'max_depth': [None, 5, 10, 20],
    'min_samples_split': [2, 5, 10]
}

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

# Ensure y_pred_rf uses predictions from the RandomForestClassifier
y_pred_rf = rm_g.predict(x_test)

acc=accuracy_score(y_test,y_pred_rf)
print("Accuracy:",acc)
prec=precision_score(y_test,y_pred_rf)
print("Precision:",prec)
rec=recall_score(y_test,y_pred_rf)
print("Recall:",rec)
f1=f1_score(y_test,y_pred_rf)
print("f1 score:",f1)

cm = confusion_matrix(y_test, y_pred_rf)
print("Confusion Matrix:\n", cm)

plt.figure(figsize=(5,4))
sns.heatmap(cm,
            annot=True,
            fmt='d',
            cmap='Greens',
            xticklabels=["Down (0)", "Up (1)"],
            yticklabels=["Down (0)", "Up (1)"])

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix - Random Forest")
plt.show()

"""# KNN classifier

"""

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

# Initialize and train the KNN classifier
knn = KNeighborsClassifier(n_neighbors=5) # You can choose an appropriate number of neighbors
knn.fit(x_train, y_train)

# Make predictions using the trained KNN model
y_pred_knn = knn.predict(x_test)

# Now calculate metrics using the binary predictions from KNN
acc = accuracy_score(y_test, y_pred_knn)
print("Accuracy:",acc)
prec = precision_score(y_test, y_pred_knn)
print("Precision:",prec)
rec = recall_score(y_test, y_pred_knn)
print("Recall:",rec)
f1 = f1_score(y_test, y_pred_knn)
print("f1 score:",f1)

cm = confusion_matrix(y_test, y_pred_knn)
print("Confusion Matrix:\n", cm)

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(5,4))
sns.heatmap(cm,
            annot=True,
            fmt='d',
            cmap='Blues',
            xticklabels=["Down (0)", "Up (1)"],
            yticklabels=["Down (0)", "Up (1)"])

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix - KNN")
plt.show()

"""# SVC"""

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

# Initialize and train the SVC classifier
svc = SVC(random_state=200) # You can add kernel or other parameters as needed
svc.fit(x_train, y_train)

# Make predictions using the trained SVC model
y_pred_svc = svc.predict(x_test)

# Now calculate metrics using the binary predictions from SVC
acc=accuracy_score(y_test,y_pred_svc)
print("Accuracy:",acc)
prec=precision_score(y_test,y_pred_svc)
print("Precision:",prec)
rec=recall_score(y_test,y_pred_svc)
print("Recall:",rec)
f1=f1_score(y_test,y_pred_svc)
print("f1 score:",f1)

cm = confusion_matrix(y_test, y_pred_svc)
print("Confusion Matrix:\n", cm)

sns.heatmap(cm, annot=True, fmt='d', cmap='Oranges')
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix - SVC")
plt.show()

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(x_train)
X_test = scaler.transform(x_test)

# Model
model = LogisticRegression()
model.fit(x_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

for c in [0.01, 0.1, 1, 10, 100]:
    model = LogisticRegression(C=c, max_iter=500)
    model.fit(X_train, y_train)
    print("C =", c, "Accuracy =", model.score(X_test, y_test))

print(pd.Series(y).value_counts())

LogisticRegression(class_weight='balanced')

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

param_grid = {
    'C': [0.01, 0.1, 1, 110, 100],
    'solver': ['lbfgs'],
    'max_iter': [1000, 2000]
}

grid = GridSearchCV(LogisticRegression(), param_grid, cv=5)
grid.fit(X_train, y_train)

print("Best Parameters:", grid.best_params_)
print("Best Accuracy:", grid.best_score_)

pip install xgboost

from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Train Test Split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Scaling (optional but safe)
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

# Model
xgb = XGBClassifier(use_label_encoder=False, eval_metric='logloss')

# Train
xgb.fit(x_train, y_train) # Corrected: train on x_train, not x_pred

# Predict
y_pred_xgb = xgb.predict(x_test)

# Metrics
print("Accuracy:", accuracy_score(y_test, y_pred_xgb))
print("Precision:", precision_score(y_test, y_pred_xgb))
print("Recall:", recall_score(y_test, y_pred_xgb))
print("F1 Score:", f1_score(y_test, y_pred_xgb))

xgb = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=5,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

xgb.fit(X_train, y_train)

from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.05, 0.1]
}

grid = GridSearchCV(XGBClassifier(eval_metric='logloss'), param_grid, cv=5)
grid.fit(X_train, y_train)

print("Best Params:", grid.best_params_)
print("Best Accuracy:", grid.best_score_)